using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GrappleGun : MonoBehaviour
{
    [SerializeField] private GameObject grappleHookPre;
    [SerializeField] private Transform gunTip;
    [SerializeField] private float shotForce = 10;
    private GameObject hook;
    private SpringJoint spring;
    private LineRenderer rope;
    public Transform camera;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetMouseButtonDown(1)) {
            Grapple();
        } else if (Input.GetMouseButtonUp(1)) {
            DeGrapple();
        }

        // Update rope positions
        if (rope) {
            rope.SetPosition(0, gunTip.position);
            rope.SetPosition(1, hook.transform.position);
        }
    }

    private void Grapple() {
        Camera cam = camera.GetComponent<Camera>();
        Ray ray = cam.ScreenPointToRay(Input.mousePosition);
        //Vector3 mousePosition = cam.ScreenToWorldPoint(Input.mousePosition);
        //Ray ray = new Ray(camera.position, camera.forward);
        RaycastHit hit;
        if (Physics.Raycast(ray, out hit, 100))
        {
            //Debug.Log("Hit " + hit.collider.name);
        }



        
            


        // Instantiate a grappling hook, send it out
        hook = Instantiate(grappleHookPre, gunTip.position, gunTip.rotation);
        hook.GetComponent<Rigidbody>().AddForce((hit.point - (gunTip.position + gunTip.right * 2 + gunTip.forward * 2)) * shotForce, ForceMode.Impulse);

        // Configure the spring
        spring = transform.root.gameObject.AddComponent<SpringJoint>();
        spring.spring = 40;
        spring.damper = 10;
        spring.autoConfigureConnectedAnchor = false;
        spring.connectedBody = hook.GetComponent<Rigidbody>();
        spring.connectedAnchor = Vector3.zero;
        spring.anchor = gunTip.position - transform.position;

        // Set up the rope
        rope = hook.GetComponent<LineRenderer>();
        rope.enabled = true;
    }
    
    private void DeGrapple() {
        // Remove the hook and the spring joint
        Destroy(hook);
        Destroy(spring);
    }
}
